const K='yn_market_ledger_v1';
let db=JSON.parse(localStorage.getItem(K)||'{"markets":[],"expenses":[]}');let view='dashboard',editId=null;
const $=s=>document.querySelector(s), save=()=>localStorage.setItem(K,JSON.stringify(db));
function fmt(d){if(!d)return'';return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}
function money(n){return '$'+Number(n||0).toFixed(2)}
function upcoming(){return db.markets.filter(m=>m.date&&new Date(m.date+'T23:59:59')>=new Date()).sort((a,b)=>a.date.localeCompare(b.date))[0]}
function attention(){return db.markets.filter(m=>!m.accepted||!m.paid||!m.contacted).slice(0,5)}
function shell(content,active=view){return `<main class="shell"><section class="hero orn"><span class="bat a">🦇</span><span class="bat b">👻</span><h1>Yesterday's<br>Nostalgia</h1><p>MARKET LEDGER</p></section>${content}</main><button class="fab btn primary" onclick="openForm()">＋</button><nav class="nav"><div class="navin">${[['dashboard','👻','Dashboard'],['markets','⚰','Markets'],['calendar','☾','Calendar'],['expenses','♱','Expenses'],['more','🦇','More']].map(x=>`<button class="${active===x[0]?'active':''}" onclick="go('${x[0]}')"><i>${x[1]}</i>${x[2]}</button>`).join('')}</div></nav>`}
function render(){let html='';if(view==='dashboard')html=dashboard();if(view==='markets')html=markets();if(view==='calendar')html=calendar();if(view==='expenses')html=expenses();if(view==='more')html=more();if(view==='form')html=form();$('#app').innerHTML=shell(html,view==='form'?'markets':view)}
function dashboard(){let n=upcoming(),a=attention();return `${n?`<section class="next orn"><div class="eyebrow">Next Market</div><h2>${esc(n.name)}</h2><div class="meta">${fmt(n.date)} · ${esc(n.city||'')} ${n.start?'· '+n.start:''}</div><div class="badge">${n.accepted?(n.paid?'ACCEPTED · PAID':'ACCEPTED · FEE DUE'):'UNFINISHED BUSINESS'}</div></section>`:`<section class="next orn empty"><strong>No upcoming markets.</strong>The dead may rest… briefly.</section>`}<div class="grid"><div class="tile orn" onclick="go('markets')"><span>☾</span><b>MARKETS</b></div><div class="tile orn" onclick="go('calendar')"><span>🗓</span><b>CALENDAR</b></div><div class="tile orn" onclick="openForm()"><span>⚰</span><b>ADD EVENT</b></div></div><section class="section orn"><h3>☠ ATTENTION NEEDED</h3>${a.length?a.map(m=>`<div class="row" onclick="openForm('${m.id}')"><div><b>${esc(m.name)}</b><div class="small">${fmt(m.date)}</div></div><div class="small">${!m.contacted?'Not contacted':!m.accepted?'Awaiting acceptance':!m.paid?'Fee unpaid':'Review'} ›</div></div>`).join(''):`<div class="empty"><strong>No unfinished business.</strong>The dead may rest.</div>`}</section>`}
function markets(){let arr=[...db.markets].sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));return `<section class="section orn"><div class="toolbar"><h3>MARKETS & MOURNING</h3><button class="btn" onclick="openForm()">+ Add</button></div>${arr.length?arr.map(m=>`<div class="card orn" onclick="openForm('${m.id}')"><div class="status">${m.accepted?'Accepted':'Interested'}${m.paid?' · Paid':''}</div><h3>${esc(m.name)}</h3><div class="small">${fmt(m.date)} · ${esc(m.city||'No town yet')}</div><div class="small">Booth ${money(m.fee)}</div></div>`).join(''):`<div class="empty"><strong>Your ledger is eerily empty.</strong>Add the next market you stumble across at 1:37 AM.</div>`}</section>`}
function calendar(){let d=new Date(),y=d.getFullYear(),mo=d.getMonth(),first=new Date(y,mo,1),days=new Date(y,mo+1,0).getDate(),pad=first.getDay(),cells='';for(let i=0;i<pad;i++)cells+='<div></div>';for(let day=1;day<=days;day++){let ds=`${y}-${String(mo+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,ms=db.markets.filter(m=>m.date===ds);cells+=`<div class="day"><b>${day}</b>${ms.map(m=>`<span class="dot">🦇 ${esc(m.name)}</span>`).join('')}</div>`}return `<section class="section orn"><h3>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'}).toUpperCase()}</h3><div class="calendar">${['S','M','T','W','T','F','S'].map(x=>`<b class="small">${x}</b>`).join('')}${cells}</div></section>`}
function expenses(){let sales=db.markets.reduce((s,m)=>s+Number(m.sales||0),0),fees=db.markets.reduce((s,m)=>s+Number(m.fee||0)+Number(m.otherExpenses||0),0),extra=db.expenses.reduce((s,e)=>s+Number(e.amount||0),0);return `<section class="section orn"><h3>THE DAMAGE & THE SPOILS</h3><div class="row"><span>Market sales</span><b class="money">${money(sales)}</b></div><div class="row"><span>Market costs</span><b>${money(fees)}</b></div><div class="row"><span>Other expenses</span><b>${money(extra)}</b></div><div class="row"><span>Recorded profit</span><b class="money">${money(sales-fees-extra)}</b></div></section><section class="section orn"><h3>QUICK EXPENSE</h3><div class="form"><label>Description</label><input id="exDesc"><label>Amount</label><input id="exAmt" type="number" step=".01"><div class="actions"><button class="btn primary" onclick="addExpense()">Record expense</button></div></div>${db.expenses.map(e=>`<div class="row"><span>${esc(e.desc)}</span><b>${money(e.amount)}</b></div>`).join('')}</section>`}
function more(){return `<section class="section orn"><h3>THE ARCHIVES</h3><p class="small">Your ledger currently lives on this device. Export a backup whenever you want a copy safe from browser-clearing gremlins.</p><div class="actions"><button class="btn primary" onclick="exportData()">Export Backup</button><label class="btn">Import Backup<input type="file" accept="application/json" onchange="importData(event)" hidden></label></div></section><p class="ghostnote">Cute little ghosts cannot be held responsible for lost paperwork.</p>`}
function form(){let m=db.markets.find(x=>x.id===editId)||{};let c=k=>m[k]?'checked':'';return `<section class="section orn form"><div class="toolbar"><h3>${m.id?'EDIT MARKET':'UNFINISHED BUSINESS'}</h3><button class="btn" onclick="go('markets')">Close</button></div><label>Event name *</label><input id="name" value="${attr(m.name)}"><label>Date</label><input id="date" type="date" value="${attr(m.date)}"><label>Town / location</label><input id="city" value="${attr(m.city)}"><label>Event hours</label><div class="checks"><input id="start" placeholder="Start (9:00 AM)" value="${attr(m.start)}"><input id="end" placeholder="End (4:00 PM)" value="${attr(m.end)}"></div><label>Organizer / host</label><input id="organizer" value="${attr(m.organizer)}"><label>Email</label><input id="email" type="email" value="${attr(m.email)}"><label>Phone</label><input id="phone" value="${attr(m.phone)}"><label>Facebook / event / application link</label><input id="link" type="url" value="${attr(m.link)}"><label>Booth fee</label><input id="fee" type="number" step=".01" value="${attr(m.fee)}"><label>Booth & setup notes</label><textarea id="setup">${esc(m.setup||'')}</textarea><label>The paper trail</label><div class="checks">${[['contacted','Contacted'],['applied','Applied'],['accepted','Accepted'],['agreement','Agreement signed'],['paid','Fee paid'],['confirmed','Confirmation received']].map(([k,t])=>`<label class="check"><input id="${k}" type="checkbox" ${c(k)}> ${t}</label>`).join('')}</div><label>Shade / indoor / electricity / rules</label><textarea id="rules">${esc(m.rules||'')}</textarea><label>Sales after market</label><input id="sales" type="number" step=".01" value="${attr(m.sales)}"><label>Other market expenses</label><input id="otherExpenses" type="number" step=".01" value="${attr(m.otherExpenses)}"><label>Would we return from the grave?</label><select id="return"><option></option>${['Absolutely','Maybe','Fuck no'].map(x=>`<option ${m.return===x?'selected':''}>${x}</option>`).join('')}</select><label>Notes</label><textarea id="notes">${esc(m.notes||'')}</textarea><div class="actions"><button class="btn primary" onclick="saveMarket()">Save to Ledger</button>${m.id?`<button class="btn danger" onclick="deleteMarket()">Bury This Record</button>`:''}</div></section>`}
function openForm(id=null){editId=id;view='form';render();scrollTo(0,0)}function go(v){view=v;editId=null;render();scrollTo(0,0)}
function saveMarket(){let old=db.markets.find(x=>x.id===editId)||{},g=id=>$('#'+id);let m={...old,id:old.id||crypto.randomUUID(),name:g('name').value.trim()||'Unnamed Market',date:g('date').value,city:g('city').value.trim(),start:g('start').value.trim(),end:g('end').value.trim(),organizer:g('organizer').value.trim(),email:g('email').value.trim(),phone:g('phone').value.trim(),link:g('link').value.trim(),fee:g('fee').value,setup:g('setup').value,rules:g('rules').value,sales:g('sales').value,otherExpenses:g('otherExpenses').value,return:g('return').value,notes:g('notes').value};['contacted','applied','accepted','agreement','paid','confirmed'].forEach(k=>m[k]=g(k).checked);let i=db.markets.findIndex(x=>x.id===m.id);if(i>=0)db.markets[i]=m;else db.markets.push(m);save();go('markets')}
function deleteMarket(){if(confirm('Bury this market record for good?')){db.markets=db.markets.filter(x=>x.id!==editId);save();go('markets')}}function addExpense(){let d=$('#exDesc').value.trim(),a=$('#exAmt').value;if(!d||!a)return;db.expenses.unshift({id:crypto.randomUUID(),desc:d,amount:a,date:new Date().toISOString()});save();render()}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='yesterdays-nostalgia-market-ledger-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert('The archives have been restored.')}catch{alert('That backup file could not be read.')}};r.readAsText(f)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s=''){return esc(s)}render();
